<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ninja.Api\Ninja.Api.csproj" />
    <ProjectReference Include="..\..\src\Ninja.Application\Ninja.Application.csproj" />
    <ProjectReference Include="..\..\src\Ninja.Infrastructure\Ninja.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Ninja.Domain\Ninja.Domain.csproj" />
  </ItemGroup>

</Project>
